// flow-typed signature: 6fd4b914c8e91d2f21140b84b9f35a34
// flow-typed version: <<STUB>>/finale-rest_v^0.1.5/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'finale-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'finale-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'finale-rest/lib/associations/belongs-to-many' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/belongs-to' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/has-many' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/has-one' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/base' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/create' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/delete' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/index' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/list' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/read' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/update' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Endpoint' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Errors' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/index' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Resource' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'finale-rest/lib/associations/belongs-to-many.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/belongs-to-many'>;
}
declare module 'finale-rest/lib/associations/belongs-to.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/belongs-to'>;
}
declare module 'finale-rest/lib/associations/has-many.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/has-many'>;
}
declare module 'finale-rest/lib/associations/has-one.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/has-one'>;
}
declare module 'finale-rest/lib/Controllers/base.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/base'>;
}
declare module 'finale-rest/lib/Controllers/create.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/create'>;
}
declare module 'finale-rest/lib/Controllers/delete.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/delete'>;
}
declare module 'finale-rest/lib/Controllers/index.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/index'>;
}
declare module 'finale-rest/lib/Controllers/list.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/list'>;
}
declare module 'finale-rest/lib/Controllers/read.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/read'>;
}
declare module 'finale-rest/lib/Controllers/update.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/update'>;
}
declare module 'finale-rest/lib/Endpoint.js' {
  declare module.exports: $Exports<'finale-rest/lib/Endpoint'>;
}
declare module 'finale-rest/lib/Errors.js' {
  declare module.exports: $Exports<'finale-rest/lib/Errors'>;
}
declare module 'finale-rest/lib/index.js' {
  declare module.exports: $Exports<'finale-rest/lib/index'>;
}
declare module 'finale-rest/lib/Resource.js' {
  declare module.exports: $Exports<'finale-rest/lib/Resource'>;
}
declare module 'finale-rest/lib/util.js' {
  declare module.exports: $Exports<'finale-rest/lib/util'>;
}
