// flow-typed signature: 804f04a4cc6ffe092ca4444e9eaa8d49
// flow-typed version: <<STUB>>/jest-mock-express_v^0.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-mock-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-mock-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-mock-express/lib/response' {
  declare module.exports: any;
}

declare module 'jest-mock-express/lib/response.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-mock-express/index' {
  declare module.exports: $Exports<'jest-mock-express'>;
}
declare module 'jest-mock-express/index.js' {
  declare module.exports: $Exports<'jest-mock-express'>;
}
declare module 'jest-mock-express/lib/response.js' {
  declare module.exports: $Exports<'jest-mock-express/lib/response'>;
}
declare module 'jest-mock-express/lib/response.test.js' {
  declare module.exports: $Exports<'jest-mock-express/lib/response.test'>;
}
