// flow-typed signature: b4e9de0cd243ef36c80f35ec46aae6d4
// flow-typed version: <<STUB>>/mock-req_v^0.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-req'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-req' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-req/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-req/index' {
  declare module.exports: $Exports<'mock-req'>;
}
declare module 'mock-req/index.js' {
  declare module.exports: $Exports<'mock-req'>;
}
declare module 'mock-req/test.js' {
  declare module.exports: $Exports<'mock-req/test'>;
}
