// flow-typed signature: 0948963ba91b528da3a5720dda616b69
// flow-typed version: <<STUB>>/rdstation-node-client_v^1.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rdstation-node-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rdstation-node-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rdstation-node-client/Gruntfile' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/lib/rdstation/client' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/lib/rdstation/conversions' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/lib/rdstation/index' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/lib/rdstation/leads' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/lib/rdstation/services' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/test/conversions' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/test/factory' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/test/leads' {
  declare module.exports: any;
}

declare module 'rdstation-node-client/test/services' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rdstation-node-client/Gruntfile.js' {
  declare module.exports: $Exports<'rdstation-node-client/Gruntfile'>;
}
declare module 'rdstation-node-client/index' {
  declare module.exports: $Exports<'rdstation-node-client'>;
}
declare module 'rdstation-node-client/index.js' {
  declare module.exports: $Exports<'rdstation-node-client'>;
}
declare module 'rdstation-node-client/lib/rdstation/client.js' {
  declare module.exports: $Exports<'rdstation-node-client/lib/rdstation/client'>;
}
declare module 'rdstation-node-client/lib/rdstation/conversions.js' {
  declare module.exports: $Exports<'rdstation-node-client/lib/rdstation/conversions'>;
}
declare module 'rdstation-node-client/lib/rdstation/index.js' {
  declare module.exports: $Exports<'rdstation-node-client/lib/rdstation/index'>;
}
declare module 'rdstation-node-client/lib/rdstation/leads.js' {
  declare module.exports: $Exports<'rdstation-node-client/lib/rdstation/leads'>;
}
declare module 'rdstation-node-client/lib/rdstation/services.js' {
  declare module.exports: $Exports<'rdstation-node-client/lib/rdstation/services'>;
}
declare module 'rdstation-node-client/test/conversions.js' {
  declare module.exports: $Exports<'rdstation-node-client/test/conversions'>;
}
declare module 'rdstation-node-client/test/factory.js' {
  declare module.exports: $Exports<'rdstation-node-client/test/factory'>;
}
declare module 'rdstation-node-client/test/leads.js' {
  declare module.exports: $Exports<'rdstation-node-client/test/leads'>;
}
declare module 'rdstation-node-client/test/services.js' {
  declare module.exports: $Exports<'rdstation-node-client/test/services'>;
}
