// flow-typed signature: c391694d9332444776de4754485fadff
// flow-typed version: <<STUB>>/string-template_v^1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-template/compile' {
  declare module.exports: any;
}

declare module 'string-template/coverage/prettify' {
  declare module.exports: any;
}

declare module 'string-template/coverage/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-template/compile.js' {
  declare module.exports: $Exports<'string-template/compile'>;
}
declare module 'string-template/coverage/prettify.js' {
  declare module.exports: $Exports<'string-template/coverage/prettify'>;
}
declare module 'string-template/coverage/sorter.js' {
  declare module.exports: $Exports<'string-template/coverage/sorter'>;
}
declare module 'string-template/index' {
  declare module.exports: $Exports<'string-template'>;
}
declare module 'string-template/index.js' {
  declare module.exports: $Exports<'string-template'>;
}
