module.exports = {
    amAuth: require('./am-auth'),
    amBootstrap: require('./am-bootstrap'),
    amController: require('./am-controller'),
    amError: require('./am-error'),
    amInvite: require('./am-invite'),
    amLeadManager: require('./am-leadManager'),
    amMailing: require('./am-mailing'),
    amModel: require('./am-model'),
    amRdStation: require('./am-rdstation'),
    amRouter: require('./am-router'),
    amSoftDelete: require('./am-softDelete'),
    amSystem: require('./am-system'),
    checkVersion: require('./check-version'),
    dateTime: require('./dateTime'),
    util: require('./util'),
    apiBootstrap: require('./apiBootstrap'),
    nodeRestful: require('./nodeRestful'),
    stats: require('./stats'),
    message: require('./message'),
    notification: require('./notification'),

    modelMongoose: require('./modelMongoose'),
    express: require('./express'),

    modelSequelize: require('./sequelize/modelSequelize'),
    jsonSchema: require('./sequelize/sequelizeJSON'),
    apiBootstrapS: require('./sequelize/apiBootstrapS'),
    auth: require('./sequelize/auth'),
    finaleRestful: require('./sequelize/finaleRestful')
};