// flow-typed signature: 330714c231ca5c59baa14aceb85371de
// flow-typed version: <<STUB>>/@app-masters/mongoose-it_v^1.0.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@app-masters/mongoose-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@app-masters/mongoose-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@app-masters/mongoose-it/lib/amCache' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/lib/mongooseCacheIt' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/lib/mongooseIt' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/lib/util' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/test/amCache.test' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/test/connectionData' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/test/mongooseCacheIt.test' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/test/mongooseIt.test' {
  declare module.exports: any;
}

declare module '@app-masters/mongoose-it/test/util.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@app-masters/mongoose-it/index' {
  declare module.exports: $Exports<'@app-masters/mongoose-it'>;
}
declare module '@app-masters/mongoose-it/index.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it'>;
}
declare module '@app-masters/mongoose-it/lib/amCache.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/lib/amCache'>;
}
declare module '@app-masters/mongoose-it/lib/mongooseCacheIt.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/lib/mongooseCacheIt'>;
}
declare module '@app-masters/mongoose-it/lib/mongooseIt.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/lib/mongooseIt'>;
}
declare module '@app-masters/mongoose-it/lib/util.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/lib/util'>;
}
declare module '@app-masters/mongoose-it/test/amCache.test.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/test/amCache.test'>;
}
declare module '@app-masters/mongoose-it/test/connectionData.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/test/connectionData'>;
}
declare module '@app-masters/mongoose-it/test/mongooseCacheIt.test.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/test/mongooseCacheIt.test'>;
}
declare module '@app-masters/mongoose-it/test/mongooseIt.test.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/test/mongooseIt.test'>;
}
declare module '@app-masters/mongoose-it/test/util.test.js' {
  declare module.exports: $Exports<'@app-masters/mongoose-it/test/util.test'>;
}
